sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

install:
   - npm install -g firebase-tools

before_script:
  - npm install

script:

after_success:
  -firebase deploy --token $FIREBASE_TOKEN

